### PR TITLE
Update Language.fr.xml

### PR DESCRIPTION
**Pull request by verturin**
those where I have a doubt still in English
I expect to see the situation.
but everything is done
there will surely corrections during premieres uses

### CODE REVIEW

**Comment by RobertoPeters** [comment]
Hi Fred,

Before issuing a pull request, please update your branche with the changes
from the master branch.
Otherwise, I won't be able to merge it automatically, because the language
file has changed.

Regards,
Robert

2015-10-28 13:56 GMT+01:00 Verturin notifications@github.com:

**Comment by verturin** [comment]
Ok

I m on holiday ne i havé ont à good network
I m looking for that next monday

Fred
Verturin

**Comment by verturin** [comment]
Sorry but where can i find the procedure to update your my  branche with the changes from the master branch.

Fred

**Comment by RobertoPeters** [comment]
Maybe the easiest way is with https://desktop.github.com/
With this application it can be done easily. (since it is developed for
github)
- Robert

2015-11-02 13:58 GMT+01:00 Verturin notifications@github.com:

**Pull request closed without merging**
